name: "pagely-deploy"
on:
  push:
jobs:
  deploy1:
    name: Deploy to Pagely - theme
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run deploy
        uses: godaddy-wordpress/pagely-deploy-action@v1
        with:
          PAGELY_DEPLOY_DEST: "/httpdocs/wp-content/themes/test"
          PAGELY_INTEGRATION_SECRET: ${{secrets.PAGELY_INTEGRATION_SECRET}}
          PAGELY_INTEGRATION_ID: ${{secrets.PAGELY_INTEGRATION_ID}}
          PAGELY_APP_ID: "48077"
          PAGELY_WORKING_DIR: "wp-content/themes/test"
  deploy2:
    name: Deploy to Pagely - plugin
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run deploy
        uses: godaddy-wordpress/pagely-deploy-action@v1
        with:
          PAGELY_DEPLOY_DEST: "/httpdocs/wp-content/plugins/test"
          PAGELY_INTEGRATION_SECRET: ${{secrets.PAGELY_INTEGRATION_SECRET}}
          PAGELY_INTEGRATION_ID: ${{secrets.PAGELY_INTEGRATION_ID}}
          PAGELY_APP_ID: "48077"
          PAGELY_WORKING_DIR: "wp-content/plugins/test"
