name: "pagely-deploy"
on:
  push:
jobs:
  deploy1:
    name: Deploy to Pagely - theme
    runs-on: ubuntu-latest
    if: contains(join(github.event.commits.*.modified, ','), 'wp-content/themes/test') || contains(join(github.event.commits.*.added, ','), 'wp-content/themes/test')
    steps:
      - uses: actions/checkout@v2
      - name: Run deploy
        uses: godaddy-wordpress/pagely-deploy-action@v1
        with:
          PAGELY_DEPLOY_DEST: "/httpdocs/wp-content/themes/test"
          PAGELY_WORKING_DIR: "wp-content/themes/test"
          PAGELY_APP_ID: "48077"
          PAGELY_INTEGRATION_SECRET: ${{ secrets.PAGELY_INTEGRATION_SECRET }}
          PAGELY_INTEGRATION_ID: ${{ secrets.PAGELY_INTEGRATION_ID }}

  deploy2:
    name: Deploy to Pagely - plugin
    runs-on: ubuntu-latest
    if: contains(join(github.event.commits.*.modified, ','), 'wp-content/plugins/test') || contains(join(github.event.commits.*.added, ','), 'wp-content/plugins/test')
    steps:
      - uses: actions/checkout@v2
      - name: Run deploy
        uses: godaddy-wordpress/pagely-deploy-action@v1
        with:
          PAGELY_DEPLOY_DEST: "/httpdocs/wp-content/plugins/test"
          PAGELY_WORKING_DIR: "wp-content/plugins/test"
          PAGELY_APP_ID: "48077"
          PAGELY_INTEGRATION_SECRET: ${{ secrets.PAGELY_INTEGRATION_SECRET }}
          PAGELY_INTEGRATION_ID: ${{ secrets.PAGELY_INTEGRATION_ID }}


