name: "pagely-deploy"
on:
  push:
    paths:
      - 'wp-content/themes/test/**'
jobs:
  deploy:
    name: Deploy to Pagely - theme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run deploy
        uses: godaddy-wordpress/pagely-deploy-action@v1
        with:
          PAGELY_DEPLOY_DEST: "/httpdocs/wp-content/themes/test"
          PAGELY_WORKING_DIR: "wp-content/themes/test"
          PAGELY_APP_ID: "48077"
          PAGELY_INTEGRATION_SECRET: ${{ secrets.PAGELY_INTEGRATION_SECRET }}
          PAGELY_INTEGRATION_ID: ${{ secrets.PAGELY_INTEGRATION_ID }}

